"""Add refresh_token to users table

Revision ID: 8c5ac0b9f3bd
Revises: 001
Create Date: 2026-02-02 11:47:45.219744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5ac0b9f3bd'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'processed_emails', ['gmail_message_id'])
    op.add_column('users', sa.Column('refresh_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_constraint(None, 'processed_emails', type_='unique')
    # ### end Alembic commands ###
